### ISSUE TITLE
matrix's mul method doesn't respect column-major rule

### ISSUE THREAD

**Issue by Jack-Ji** [ziglibs/zlm#7]
Hi guys, I'm experimenting opengl using zlm, and the matrix part confuses me a little.
If my understanding is right, zlm's matrix is using column-major style like glm/opengl, 
as utility functions like createLookAt/createPerspective are token from glm. However,
the mul method of matrix is using row-major style instead, which is bit confusing and
caused different mul order when composing mvp matrix:

* in glm:
mvp = project * view * model

* in zlm:
mvp = model.mul(view).mul(project)

Is it an accident or by design?

**Comment by MasterQ32** [comment]
This is by-design, as this is the "natural" transformation order (you first transform by the model, then by the view, then by projection)

**Comment by Jack-Ji** [comment]
Got it, thanks!
